apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jira-wait-for-status
description: "Wait for a Jira issue to reach specific status(es)"
inputs:
  jira-url:
    description: "Jira instance URL (e.g., https://your-domain.atlassian.net)"
    required: true
  jira-username:
    description: "Jira username or email address"
    required: true
  jira-token:
    description: "Jira API token"
    required: true
  issue-key:
    description: "Issue key to monitor"
    required: true
  target-status:
    description: "Comma-separated list of target statuses to wait for"
    required: true
  timeout-minutes:
    description: "Timeout in minutes"
    default: "10"
    required: false
  poll-interval-seconds:
    description: "Poll interval in seconds"
    default: "30"
    required: false

outputs:
  result:
    value: ${{ steps.wait-status.outputs.result }}
    description: "Result of the wait operation (success or timeout)"
  final-status-summary:
    value: ${{ steps.wait-status.outputs.final-status-summary }}
    description: "Final status of the issue"

runs:
  using: composite
  steps:
    - id: wait-status
      name: Wait for Status Change
      uses: docker://cloudbeesdemo/jira-actions:latest
      shell: sh
      run: |
        /app/jira-actions wait-for-status \
          --url "${{ inputs.jira-url }}" \
          --username "${{ inputs.jira-username }}" \
          --token "${{ inputs.jira-token }}" \
          --issue-key "${{ inputs.issue-key }}" \
          --target-status "${{ inputs.target-status }}" \
          --timeout-minutes "${{ inputs.timeout-minutes }}" \
          --poll-interval-seconds "${{ inputs.poll-interval-seconds }}" \
          --verbose
